# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 manop55555
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "manop55555"
    commit-message:
      prefix: "ci"
      include: "scope"
