#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 manop55555
#
# Mock release-install smoke test. Builds a release-style tarball
# layout from the just-compiled abcpwn binary plus the tracked
# LICENSE / README / completions / docs, extracts it into a temp
# prefix, and verifies the canonical "abcpwn --version" round-trips.
# This is the cheapest signal that the documented archive layout is something we can
# actually produce.
#
# Usage: test_installer.sh <abcpwn-binary> <source-root>

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "[-] usage: $0 <abcpwn-binary> <source-root>" >&2
    exit 2
fi

ABCPWN_BIN="$1"
SOURCE_ROOT="$2"

if [ ! -x "$ABCPWN_BIN" ]; then
    echo "[-] $ABCPWN_BIN is not executable" >&2
    exit 1
fi

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

# Step 1: assemble the canonical archive layout.
release_root="$work_dir/abcpwn-linux-x86_64"
mkdir -p "$release_root"
cp "$ABCPWN_BIN"                          "$release_root/abcpwn"
cp "$SOURCE_ROOT/LICENSE"                 "$release_root/LICENSE"
cp "$SOURCE_ROOT/LICENSE-THIRD-PARTY.md"  "$release_root/LICENSE-THIRD-PARTY.md"
cp "$SOURCE_ROOT/README.md"               "$release_root/README.md"
cp "$SOURCE_ROOT/CHANGELOG.md"            "$release_root/CHANGELOG.md"
cp "$SOURCE_ROOT/BUILDING.md"             "$release_root/BUILDING.md"
cp "$SOURCE_ROOT/SECURITY.md"             "$release_root/SECURITY.md"
if [ -d "$SOURCE_ROOT/completions" ]; then
    cp -r "$SOURCE_ROOT/completions" "$release_root/completions"
fi
# man page is generated by step 26; ship as empty placeholder so the
# layout matches without claiming we already produce a man page.
mkdir -p "$release_root/share"

# Step 2: tar / extract round-trip.
tar -C "$work_dir" -czf "$work_dir/abcpwn.tar.gz" abcpwn-linux-x86_64
extract_dir="$work_dir/extracted"
mkdir -p "$extract_dir"
tar -C "$extract_dir" -xzf "$work_dir/abcpwn.tar.gz"

# Step 3: verify the layout contains the documented top-level files.
# The release.yml staging step ships the same set; this asserts the
# user can read CHANGELOG, BUILDING, SECURITY, third-party licenses,
# and completions without bouncing back to GitHub after extraction.
for expected in \
    abcpwn \
    LICENSE \
    LICENSE-THIRD-PARTY.md \
    README.md \
    CHANGELOG.md \
    BUILDING.md \
    SECURITY.md \
    completions
do
    if [ ! -e "$extract_dir/abcpwn-linux-x86_64/$expected" ]; then
        echo "[-] release layout missing $expected" >&2
        exit 1
    fi
done

# Step 4: the extracted binary still reports the expected version.
# The --version output is a multi-line block beginning
# with the compact banner header followed by the "abcpwn v<semver>"
# line; match the latter to confirm provenance fields round-trip
# through the tarball.
version_out="$("$extract_dir/abcpwn-linux-x86_64/abcpwn" --version 2>&1)"
case "$version_out" in
    *"abcpwn v0.1.0"*) ;;
    *) echo "[-] unexpected --version output: $version_out" >&2; exit 1 ;;
esac

# Step 5: the extracted binary still answers a basic command.
out="$("$extract_dir/abcpwn-linux-x86_64/abcpwn" --no-banner errno 13 2>&1 || true)"
case "$out" in
    *EACCES*) ;;
    *) echo "[-] extracted binary did not surface EACCES for errno 13"; exit 1 ;;
esac

echo "[+] installer mock OK: release layout, tarball round-trip, --version, errno"
